### ISSUE TITLE
Remove unused firebase imports?

### ISSUE THREAD

**Issue by nipuna-g** [AngularFirebase/118-redux-from-scratch-rxjs#1]
When trying to run a fresh clone of this project, there is an error in the app.moule.ts: 29. 

Currently, it's looking for `firebase` in `../env`

```
// Delete Me!
import { firebase } from '../env';
```

Should this along with the other firebase references be removed from this project? 

PS: Thanks for the the great tutorial.

**Comment by codediodeio** [comment]
Yes, those are from a base project and not necessary, so go ahead and remove them.
